use jue_world::integration::physics::compile_to_physics_world;
use jue_world::parser::parse;
use jue_world::trust_tier::TrustTier;

fn main() {
    let source = "(lambda (x) x)";

    println!("Testing simple lambda: {}", source);

    let ast = parse(source).expect("Parse failed");
    let (bytecode, constants) =
        compile_to_physics_world(&ast, TrustTier::Empirical).expect("Compile failed");

    println!("Generated bytecode:");
    for (i, op) in bytecode.iter().enumerate() {
        println!("{}: {:?}", i, op);
    }

    println!("\nConstants: {:?}", constants);
}
