use crate::grammar::PythonParser; // generated by Pest
use crate::lexer::{Lexer, Token};
use pest::iterators::Pair;
use pest::Parser;

#[derive(Debug)]
pub enum AstNode {
    Number(String),
    String(String),
    Name(String),
    Expr(Vec<AstNode>),
    Statement(Box<AstNode>),
    File(Vec<AstNode>),
}

pub fn parse_tokens(tokens: Vec<Token>) -> AstNode {
    // For now: naive builder that converts Name/Number/String tokens to AST
    let mut stmts = Vec::new();
    let mut current_expr = Vec::new();

    for tok in tokens {
        match tok {
            Token::Name(n) => current_expr.push(AstNode::Name(n)),
            Token::Number(n) => current_expr.push(AstNode::Number(n)),
            Token::String(s) => current_expr.push(AstNode::String(s)),
            Token::Symbol(_) => (), // extend later
            Token::Newline => {
                if !current_expr.is_empty() {
                    stmts.push(AstNode::Statement(Box::new(AstNode::Expr(current_expr))));
                    current_expr = Vec::new();
                }
            }
            _ => {}
        }
    }

    AstNode::File(stmts)
}
